
const clinicLocations = [
    {
        id: 1,
        name: "Medical Center",
        address: "123 Main Street, Houston, TX, 77803",
        state: "Texas",
        city: "Houston",
        phone: "(111) 111-1111",
        email: "medi.center@example.com",
        hours: "Mon-Fri: 8am-6pm, Sat-Sun: Closed",
    },
    {
        id: 2,
        name: "Community Clinic",
        address: "124 Blake St, Houston, TX,  77502",
        state: "Texas",
        city: "Houston",
        phone: "(222) 222-2222",
        email: "comm.clinic@example.com",
        hours: "Mon-Fri: 8am-5pm, Sat-Sun: 9am-1pm",
    },
    {
        id: 3,
        name: "UH Clinic",
        address: "4349 Martin Luther King Blvd, Houston, TX 77204",
        state: "Texas",
        city: "Houston",
        phone: "(333) 333-3333",
        email: "UHClinic@example.com",
        hours: "Mon-Thu: 8am-7pm, Fri: 8am-5pm, Sat-Sun: Closed",
    },
    {
        id: 4,
        name: "Main Street Medical Center",
        address: "123 Main Street, San Francisco, CA 94110",
        state: "California",
        city: "San Francisco",
        phone: "(444) 444-4444",
        email: "main.medi@example.com",
        hours: "Mon-Fri: 8am-6pm, Sat: 9am-7pm, Sun: Closed",
    },
    {
        id: 5,
        name: "Westside Health Clinic",
        address: "456 West Avenue, Los Angeles, CA 90001",
        state: "California",
        city: "Los Angeles",
        phone: "(999) 999-1111",
        email: "west.clinic@example.com",
        hours: "Mon-Fri: 7am-8pm, Sat-Sun: 9am-2pm",
    },
    {
        id: 6,
        name: "RestoreHealth Clinic",
        address: "888 Waterfront Dr, Seattle, WA 98104",
        state: "Washington",
        city: "Seattle",
        phone: "(888) 888-1111",
        email: "restoreHealth@example.com",
        hours: "Mon-Fri: 7am-7pm, Sat-Sun: 8am-5pm",
    },
    {
        id: 7,
        name: "Vibrant Clinic",
        address: "789 Central Blvd, Seattle, WA 98101",
        state: "Washington",
        city: "Seattle",
        phone: "(777) 777-1111",
        email: "vib.clinic@example.com",
        hours: "Mon-Fri: 7am-6pm, Sat-Sun: 8am-12pm",
    },
    {
        id: 8,
        name: "Swift Aid Clinic",
        address: "3479 Oakdale Avenue, Lake Placid, FL 33852",
        state: "Florida",
        city: "Lake Placid",
        phone: "(222) 444-1111",
        email: "swiftAid.clinic@example.com",
        hours: "Mon-Fri: 7am-8pm, Sat-Sun: 8am-3pm",
    },
    {
        id: 9,
        name: "Care Point Clinic",
        address: "3444 Pleasant Hill Road, Pahokee, FL 33476",
        state: "Florida",
        city: "Pahokee",
        phone: "(321) 123-1234",
        email: "carepoint.clinic@example.com",
        hours: "Mon-Fri: 7am-8pm, Sat-Sun: 8am-4pm",
    },
    {
        id: 10,
        name: "Harmony Clinic",
        address: "2458 Hartway Street, Browns Valley, SD 56219",
        state: "South Dakota",
        city: "Browns Valley",
        phone: "(432) 234-4345",
        email: "harmonyClinic.clinic@example.com",
        hours: "Mon-Fri: 7am-7pm, Sat-Sun: 8am-2pm",
    },
    {
        id: 11,
        name: "Vitality Clinic",
        address: "4230 Elsie Drive, Roscoe, SD 57471",
        state: "South Dakota",
        city: "Roscoe",
        phone: "(456) 654-4567",
        email: "vitality.clinic@example.com",
        hours: "Mon-Fri: 7am-8pm, Sat-Sun: 8am-4pm",
    }
    
];

export default clinicLocations;